-- V1 — esquema inicial da NorteShopMoz.
--
-- Gerado a partir das entidades JPA atuais e escrito de forma idempotente
-- (CREATE TABLE IF NOT EXISTS, constraints protegidas contra duplicação), para
-- poder ser aplicado sem risco tanto sobre uma base de dados NOVA como sobre
-- uma já existente, criada pelo antigo spring.jpa.hibernate.ddl-auto=update.
--
-- A partir daqui o schema é gerido por migrações versionadas. Alterações
-- futuras fazem-se em novos ficheiros V2__*.sql, V3__*.sql, … e o Hibernate
-- corre em ddl-auto=validate (nunca altera schema — ver application.yaml).

create table if not exists address_book_entries (
    is_default boolean not null,
    lat float(53),
    lng float(53),
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    phone varchar(40) not null,
    user_id varchar(40) not null,
    label varchar(60),
    city varchar(80) not null,
    full_name varchar(80) not null,
    province varchar(80) not null,
    address varchar(200) not null,
    primary key (id)
);

create table if not exists categories (
    emoji varchar(8),
    slug varchar(60) not null,
    name varchar(80) not null,
    description varchar(300),
    image varchar(500),
    primary key (slug)
);

create table if not exists coupons (
    active boolean not null,
    discount_value numeric(12,2) not null,
    minimum_subtotal numeric(12,2),
    usage_limit integer not null,
    used_count integer not null,
    expires_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    discount_type varchar(10) not null,
    code varchar(40) not null unique,
    primary key (id)
);

create table if not exists favorites (
    product_id varchar(40) not null,
    user_id varchar(40) not null,
    primary key (product_id, user_id)
);

create table if not exists newsletter_subscribers (
    active boolean not null,
    id bigint generated by default as identity,
    subscribed_at timestamp(6) with time zone not null,
    name varchar(80),
    email varchar(200) not null unique,
    primary key (id)
);

create table if not exists orders (
    discount numeric(12,2) not null,
    shipping numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    total numeric(12,2) not null,
    date timestamp(6) with time zone not null,
    status varchar(30) not null check ((status in ('PEDIDO_RECEBIDO','PAGAMENTO_CONFIRMADO','EM_PREPARACAO','ENVIADO','EM_TRANSITO','ENTREGUE','CANCELADO'))),
    coupon_code varchar(40),
    id varchar(40) not null,
    phone varchar(40) not null,
    user_id varchar(40),
    city varchar(80),
    payment_method varchar(80) not null,
    payment_reference varchar(80),
    province varchar(80) not null,
    full_name varchar(120) not null,
    email varchar(150),
    address varchar(300) not null,
    notes varchar(500),
    primary key (id)
);

create table if not exists order_items (
    position integer check ((position>=0)),
    price numeric(12,2) not null,
    qty integer not null,
    id bigint generated by default as identity,
    order_id varchar(40) not null,
    product_id varchar(40) not null,
    variant varchar(60),
    slug varchar(120) not null,
    name varchar(200) not null,
    image varchar(500),
    primary key (id)
);

create table if not exists products (
    bestseller boolean not null,
    deal_of_day boolean not null,
    featured boolean not null,
    free_shipping boolean not null,
    is_new boolean not null,
    old_price numeric(12,2),
    price numeric(12,2) not null,
    rating float(53) not null,
    rating_count integer not null,
    sold integer not null,
    stock integer not null,
    created_at timestamp(6) with time zone,
    id varchar(40) not null,
    brand varchar(60),
    category varchar(60) not null,
    slug varchar(120) not null unique,
    name varchar(200) not null,
    short_description varchar(300) not null,
    badges jsonb not null,
    delivery_days jsonb not null,
    description jsonb not null,
    images jsonb not null,
    specs jsonb not null,
    tags jsonb not null,
    variants jsonb,
    primary key (id)
);

create table if not exists reviews (
    rating integer not null,
    verified boolean not null,
    date timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    product_id varchar(40) not null,
    author varchar(80) not null,
    title varchar(120),
    comment varchar(600) not null,
    primary key (id)
);

create table if not exists user_carts (
    user_id varchar(64) not null,
    items jsonb not null,
    primary key (user_id)
);

create table if not exists users (
    email_verified boolean default false not null,
    notif_email_news boolean default false not null,
    notif_email_offers boolean default true not null,
    notif_email_order boolean default true not null,
    notif_whatsapp_offers boolean default false not null,
    notif_whatsapp_order boolean default true not null,
    verification_code_attempts int default 0 not null,
    verification_code varchar(6),
    created_at timestamp(6) with time zone not null,
    reset_token_expiry timestamp(6) with time zone,
    verification_token_expiry timestamp(6) with time zone,
    auth_provider varchar(20) default 'EMAIL' not null,
    role varchar(20) not null,
    phone varchar(30),
    reset_token varchar(64),
    verification_token varchar(64),
    full_name varchar(100) not null,
    password_hash varchar(100) not null,
    email varchar(150) not null unique,
    avatar TEXT,
    id varchar(255) not null,
    primary key (id)
);

-- Chaves estrangeiras. Só são criadas quando a coluna ainda não tem uma FK,
-- para que a migração seja aplicável tanto sobre um esquema novo como sobre um
-- já existente (criado pelo antigo ddl-auto=update, que já criou estas FKs com
-- nomes gerados pelo Hibernate). Sem esta verificação criavam-se FKs
-- duplicadas sobre a mesma coluna.
do $$
begin
    if not exists (
        select 1
        from pg_constraint c
        join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any (c.conkey)
        where c.conrelid = 'order_items'::regclass
          and c.contype = 'f'
          and a.attname = 'order_id'
    ) then
        alter table order_items add constraint fk_order_items_order
            foreign key (order_id) references orders;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint c
        join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any (c.conkey)
        where c.conrelid = 'reviews'::regclass
          and c.contype = 'f'
          and a.attname = 'product_id'
    ) then
        alter table reviews add constraint fk_reviews_product
            foreign key (product_id) references products;
    end if;
end $$;
